Refactor shared logic into function
Reviewers: O2 Material Motion, #material_motion, featherless

Reviewed By: O2 Material Motion, #material_motion, featherless

Tags: #material_motion

Differential Revision: http://codereview.cc/D2738

diff --git a/contributor_tools/dir/dir b/contributor_tools/dir/dir
--- a/contributor_tools/dir/dir
+++ b/contributor_tools/dir/dir
@@ -19,26 +19,19 @@ find_path() {
   full_reponame="material-motion-$short_reponame"
   parent_dir="$(dirname $ROOT_DIR)"
 
-  suffixes=("" "-android" "-objc" "-swift" "-js")
-  exact_matches=()
-
   # Look for exact exact_matches.
+  suffixes=("" "-android" "-objc" "-swift" "-js")
+  matches=()
   for suffix in "${suffixes[@]}"; do
     if [ -d "$parent_dir/$full_reponame$suffix" ]; then
-      exact_matches+=("$parent_dir/$full_reponame$suffix")
+      matches+=("$parent_dir/$full_reponame$suffix")
     elif [ -d "$parent_dir/$short_reponame$suffix" ]; then
-      exact_matches+=("$parent_dir/$short_reponame$suffix")
+      matches+=("$parent_dir/$short_reponame$suffix")
     fi
   done
 
-  if [[ "${#exact_matches[@]}" -eq "1" ]]; then
-    echo "${exact_matches[0]}"
-    exit 0
-  elif [[ "${#exact_matches[@]}" -gt "1" ]]; then
-    echo "Ambiguous matches, please specify a suffix manually. Found:" >&2
-    printf '%s\n' "${exact_matches[@]}" >&2
-    exit 1
-  fi
+  exact_matches=$( IFS=$'\n'; echo "${matches[*]}" )
+  _print_matches "$exact_matches"
 
   # Look for acronyms.
   word="[a-zA-Z]*"
@@ -53,28 +46,27 @@ find_path() {
   regex="$regex.*"
 
   acro_matches=$(find "$parent_dir" -maxdepth 1 -type d -regex "$regex")
-  count=$(echo "$acro_matches" | sed '/^\s*$/d' | wc -l) # Count non-empty lines.
-  if [ "$count" -eq "1" ]; then
-    echo "$acro_matches"
-    exit 0
-  elif [ "$count" -gt "1" ]; then
-    echo "Ambiguous matches, please provide a more specific query. Found:" >&2
-    echo "$acro_matches" >&2
-    exit 1
-  fi
+  _print_matches "$acro_matches"
 
   # Look for fuzzy matches.
   fuzzy_matches=$(find "$parent_dir" -maxdepth 1 -type d -name "*"$short_reponame"*")
-  count=$(echo "$fuzzy_matches" | sed '/^\s*$/d' | wc -l) # Count non-empty lines.
+  _print_matches "$fuzzy_matches"
+
+  # Failed to find any matches.
+  echo "No matches found." >&2
+  exit 1
+}
+
+_print_matches() {
+  matches="$1"
+  count=$(echo "$matches" | sed '/^\s*$/d' | wc -l) # Count non-empty lines.
+
   if [ "$count" -eq "1" ]; then
-    echo "$parent_dir/$fuzzy_matches"
+    echo "$matches"
     exit 0
   elif [ "$count" -gt "1" ]; then
     echo "Ambiguous matches, please provide a more specific query. Found:" >&2
-    echo "$fuzzy_matches" >&2
-    exit 1
-  else
-    echo "No matches found." >&2
+    echo "$matches" >&2
     exit 1
   fi
 }
